### ISSUE TITLE
Mongoose finding undefined uri parameter instead of string

### ISSUE THREAD

**Issue by CurbYourStrangeness** [CurbYourStrangeness/twitter-clone#2]
On the OSX machine I'm working on, I keep receiving error messages related to the following:

The uri parameter in server/index.js is undefined even though I'm fairly certain I'm feeding it a string.

I tried interpreting this article to solve:
https://stackoverflow.com/questions/38485575/best-way-to-connect-to-mongodb-using-node-js/38493142#38493142

But was not certain how to apply code that might make the boilerplate work.

Help requested!

**Comment by CurbYourStrangeness** [comment]
Been testing out code but I'm pretty sure it's not plug and play.

**Comment by cdrani** [comment]
@CurbYourStrangeness: This is a simple semantic (spelling) error:
In `.env`:
> MONGDB_URL=

And in the server `index.js`:
> process.env.MONGODB_URL

Also you don't need to require `dotenv` twice. Just use the last one. I would also recommend placing the `node_modules` folder and `.env` file in a `.gitignore` file.

**Comment by CurbYourStrangeness** [comment]
Thank you!

**Comment by cdrani** [comment]
No problem. You should also close this issue.

**Comment by cdrani** [comment]
One more thing. I noticed that you have added a `.gitignore` file now, but `node_modules` and `.env` are still included in git version control and thusly, in this repo as it has been cached. Here's how to remove them:
`git rm -r --cached node_modules .env`
